Firescore.Router.map(function () {
    // Autogenerated
    this.resource('bars', function(){
        this.resource('bar', { path: '/:bar_id' }, function(){
            this.route('edit');
        });
        this.route('create');
    });

    // Manual
    this.resource('games', function () {
        this.resource('game', { path: '/:game_id' }, function () {
        });
        this.route('list', { path: '/' });
        this.route('new');
    }); // games resource
});
